spring:
  profiles:
    active: prod   # ⭐ Docker run에서 설정 안 해도 prod 실행됨
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  mapper-locations: mybatis/mapper/*.xml
  type-aliases-package: com.multi.restproduct.**.dto
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

springdoc:
  group-configs:
    - group: all
      paths-to-match: /**

logging:
  level:
    root: INFO
    com.multi.restproduct: DEBUG
    org.springframework.security: DEBUG

# --- LOCAL PROFILE (실행 안 됨, 참고용) ---
---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:log4jdbc:mysql://localhost:13306/scott
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

---
# --- PROD PROFILE (Jenkins sed 로 치환됨) ---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${DB_PROD_URL}        # sed로 실제 URL 로 치환
    username: ${DB_PROD_USER}  # sed로 치환
    password: ${DB_PROD_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}   # sed로 치환
        secret-key: ${AWS_SECRET_KEY}   # sed로 치환
      s3:
        bucket: sample-s3-multi66614
        base-url: https://sample-s3-multi66614.s3.eu-west-3.amazonaws.com/products/
      region:
        static: eu-west-3
      stack:
        auto: false

jwt:
  issuer: ${JWT_ISSUER}     # sed로 치환됨
  secret: ${JWT_SECRET}
