server:
  port: 8090

mybatis:
  mapper-locations: mybatis/mapper/*.xml
  type-aliases-package: com.multi.restproduct.**.dto
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

springdoc:
  group-configs:
    - group: all
      paths-to-match: /**

---

###############################################################
#  üöÄ LOCAL PROFILE (LOCAL Í∞úÎ∞ú ÌôòÍ≤Ω)
###############################################################
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:log4jdbc:mysql://localhost:13306/scott
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      S3:
        bucket: sample-s3-multi66614
        base-url: https://sample-s3-multi66614.s3.eu-west-3.amazonaws.com/products/
      region:
        static: eu-west-3
      stack:
        auto: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    root: INFO
    com.multi.restproduct: DEBUG
    org.springframework.security: DEBUG
    jdbc:
      resultset: OFF
      audit: OFF
      connection: OFF


---

###############################################################
#  üöÄ PROD PROFILE (Ïö¥ÏòÅ / AWS EC2 / Docker ÌôòÍ≤Ω)
###############################################################
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${DB_PROD_URL}
    username: ${DB_PROD_USER}
    password: ${DB_PROD_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      S3:
        bucket: sample-s3-multi66614
        base-url: https://sample-s3-multi66614.s3.eu-west-3.amazonaws.com/products/
      region:
        static: eu-west-3
      stack:
        auto: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    root: INFO
    com.multi.restproduct: INFO

jwt:
  issuer: ${jwt.issuer}
  secret: ${jwt.secret}